# Generated by Django 4.2.3 on 2024-11-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
